DROP FUNCTION IF EXISTS GetUser
DROP FUNCTION IF EXISTS GetUserTransactions
DROP FUNCTION IF EXISTS GetLock
DROP FUNCTION IF EXISTS GetUserCurrentParkingProcesses
DROP FUNCTION IF EXISTS GetUserPastParkingProcesses

CREATE FUNCTION GetUser(@user_id UNIQUEIDENTIFIER)
RETURNS TABLE
AS
RETURN (SELECT * FROM Users WHERE id = @user_id)

CREATE FUNCTION GetUserTransactions(@user_id UNIQUEIDENTIFIER)
RETURNS TABLE
AS
RETURN (SELECT * FROM Transactions WHERE user_id = @user_id)

CREATE FUNCTION GetLock(@lock_id UNIQUEIDENTIFIER)
RETURNS TABLE
AS
RETURN (SELECT * FROM Locks WHERE id = @lock_id)

CREATE FUNCTION GetUserCurrentParkingProcesses(@user_id UNIQUEIDENTIFIER)
RETURNS TABLE
AS
RETURN (SELECT * FROM ParkingProcesses WHERE user_id = @user_id AND end_time IS NULL)

CREATE FUNCTION GetUserPastParkingProcesses(@user_id UNIQUEIDENTIFIER)
RETURNS TABLE
AS
RETURN (SELECT * FROM ParkingProcesses WHERE user_id = @user_id AND end_time IS NOT NULL)